Repository connect-foundation/2019-09, pull requests merged in 2019-12, with the labels that each got.

#314 [develop <- fix-chatting-panel-rerendering]
  client/src/presentation/components/ChattingRow.jsx
  client/src/presentation/components/ChattingWindow.jsx
  client/src/presentation/components/Message.jsx
  client/src/presentation/components/Nickname.jsx
  server/package.json
  server/socket/handlers/sendChattingMessageHandler.js
  yarn.lock
Labels: fe, issue, react

#327 Docs : 4주차 데모 추가 README.md
  README.md
Labels: docs

#329 [develop <- mobile-view] merge
  client/public/index.html
  client/src/assets/exit.png
  client/src/config.js
  client/src/presentation/components/Buttons/ExitButton.jsx
  client/src/presentation/components/ChattingWindow.jsx
  client/src/presentation/components/PlayerProfile.jsx
  client/src/presentation/components/Timer.jsx
  client/src/presentation/containers/ChattingPanel.jsx
  client/src/presentation/containers/MobileChattingPanel.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/containers/index.js
  client/src/presentation/pages/Game.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/presentation/pages/Game/style.js
  client/src/service/GameManager.js
  client/src/store/globalReducer.js
  client/src/store/globalState.js
  server/socket/gameController.js
Labels: fe, mobile, refactor

#326 [develop <- game system refactor] 게임 시스템 리팩토링
  client/src/presentation/components/PlayerProfile.jsx
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/StreamingManager.js
  client/src/service/socket/SocketClient.js
  server/app.js
  server/bin/www
  server/config.js
  server/gameService/GameManager.js
  server/gameService/Player.js
  server/gameService/eventHandlers/askSocketIdHandler.js
  server/gameService/eventHandlers/connectPeerHandler.js
  server/gameService/eventHandlers/disconnectingHandler.js
  server/gameService/eventHandlers/index.js
  server/gameService/eventHandlers/matchHandler.js
  server/gameService/eventHandlers/sendCandidateHandler.js
  server/gameService/eventHandlers/sendChattingMessageHandler.js
  server/gameService/eventHandlers/sendDescriptionHandler.js
  server/gameService/eventHandlers/sendReadyHandler.js
  server/gameService/gameController.js
  server/gameService/index.js
  server/gameService/io.js
  server/gameService/roomController.js
  server/old-socket/index.js
  server/old-socket/utils.js
  server/socket/gameController.js
  server/socket/handlers/disconnectingHandler.js
  server/socket/handlers/index.js
  server/socket/handlers/matchHandler.js
  server/socket/handlers/sendReadyHandler.js
  server/socket/index.js
  server/socket/io.js
  server/socket/rooms.js
  server/utils/colorGenerator.js
Labels: be, refactor, socket

#332 [develop <- mobile-view] 코드리뷰 사항 반영
  client/src/presentation/components/PlayerProfile.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/service/GameManager.js
  client/src/store/globalReducer.js
  client/src/store/globalState.js
Labels: fe, mobile

#338 [develop <- ranking-presentation] 랭킹 페이지 개발
  .gitignore
  client/src/App.jsx
  client/src/config.js
  client/src/presentation/components/RankPodium.jsx
  client/src/presentation/components/RankingRow.jsx
  client/src/presentation/components/index.js
  client/src/presentation/containers/BottomRankPanel.jsx
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/containers/TopRankPanel.jsx
  client/src/presentation/containers/index.js
  client/src/presentation/pages/Ranking/index.js
  client/src/presentation/pages/Ranking/style.js
  client/src/presentation/pages/index.js
  client/src/utils/styleColors.js
Labels: fe, ranking

#342 [develop <- menu-mobile-view-refactor] 메인페이지 모바일 뷰 리팩토링
  client/src/presentation/components/Buttons/MenuButton.jsx
  client/src/presentation/components/Description.jsx
  client/src/presentation/components/Title.jsx
  client/src/presentation/containers/Introduction.jsx
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/pages/MainPage.jsx
Labels: fe, main page, react

#345 [develop <- feature-database] merge
  docker-compose.yml
  mysql.cnf
  sample.env
  server/bin/www
  server/config.js
  server/databaseFiles/DatabaseManager.js
  server/databaseFiles/connection.js
  server/databaseFiles/databaseModels/Quiz.js
  server/databaseFiles/databaseModels/Ranking.js
  server/databaseFiles/databaseModels/index.js
  server/databaseFiles/databaseModels/seeder/index.js
  server/databaseFiles/databaseModels/seeder/quizzes.csv
  server/package-lock.json
  server/package.json
Labels: be, database, setup

#349 [develop <- game-message-presentation] 비디오 위 표시 컴포넌트/컨테이너 등 구현
  client/src/assets/cat.gif
  client/src/config.js
  client/src/presentation/components/CenterTimer.jsx
  client/src/presentation/components/GameMessageBox.jsx
  client/src/presentation/components/ScoreBoardScoreRow.jsx
  client/src/presentation/components/Timer.jsx
  client/src/presentation/components/index.js
  client/src/presentation/containers/ScoreBoard.jsx
  client/src/presentation/containers/StreamingPanel.jsx
  client/src/presentation/containers/StreamingPanel/index.js
  client/src/presentation/containers/StreamingPanel/presenter.js
  client/src/presentation/containers/StreamingPanel/style.js
  client/src/presentation/containers/WordCandidates.jsx
  client/src/presentation/containers/index.js
  client/src/presentation/pages/Game/index.js
  server/bin/www
Labels: fe, ingame, react

#359 Fix mobile view
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/containers/StreamingPanel/style.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/presentation/pages/Game/style.js
Labels: fe, react

#370 [develop <- pair-game-system] merge
  client/public/reset.css
  client/src/presentation/pages/Game/index.js
  client/src/service/ClientManager.js
  client/src/service/StreamingManager.js
  client/src/service/WebRTCManager.js
  server/service/game/GameManager.js
Labels: be, bug, fe, publishing

#371 [demo-bug-fix <- leave-start-bug-fix] merge
  server/service/game/eventHandlers/disconnectingHandler.js
Labels: fix

#373 [demo-bug-fix <- nickname-bug-fix] 닉네임 관련 버그 수정
  client/src/config.js
  client/src/presentation/components/TextInput.jsx
  client/src/presentation/containers/Menu.jsx
Labels: bug, fe, react

#375 [demo-bug-fix <- leave-start-bug-fix] merge
  server/service/game/eventHandlers/disconnectingHandler.js
Labels: be, bug

#376 [demo-bug-fix <- chatting-bug-fix] 채팅 무한대 이슈 해결
  client/src/config.js
  client/src/presentation/components/InputWindow.jsx
  client/src/presentation/components/MessageInput.jsx
  client/src/service/ChattingManager.js
  server/config.js
  server/service/game/eventHandlers/sendChattingMessageHandler.js
  server/utils/chatUtils.js
Labels: be, bug, fe, react

#380 [develop <- demo-bug-fix] merge
  client/src/config.js
  client/src/presentation/components/InputWindow.jsx
  client/src/presentation/components/MessageInput.jsx
  client/src/presentation/components/TextInput.jsx
  client/src/presentation/containers/Menu.jsx
  client/src/service/ChattingManager.js
  server/config.js
  server/service/game/eventHandlers/disconnectingHandler.js
  server/service/game/eventHandlers/sendChattingMessageHandler.js
  server/utils/chatUtils.js
Labels: be, bug, fe

#405 [develop <- ios-video-bug-fix] video 태그에 빠져있던 playsInline 옵션 추가
  client/src/presentation/components/StreamerVideo.jsx
Labels: fe, fix, mobile, react

#403 [develop <- feature action creator] action creator 구현
  client/src/actions/index.js
  client/src/constants/actionTypes.js
  client/src/constants/events.js
  client/src/presentation/components/Buttons/SendButton.jsx
  client/src/presentation/components/InputWindow.jsx
  client/src/presentation/components/MessageInput.jsx
  client/src/presentation/containers/ChattingPanel.jsx
  client/src/presentation/containers/StreamingPanel/index.js
  client/src/presentation/containers/StreamingPanel/presenter.js
  client/src/service/ChattingManager.js
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/StreamingManager.js
  client/src/store/globalReducer.js
  client/src/store/globalState.js
Labels: fe, react

#401 [develop <- feature-nickname-exception-handling] 닉네임 입력 및 저장 예외 처리
  client/src/config.js
  client/src/presentation/components/InputWindow.jsx
  client/src/presentation/containers/ChattingPanel.jsx
  client/src/presentation/pages/MainPage.jsx
  client/src/service/ChattingManager.js
  client/src/utils/browserLocalStorage.js
  server/config.js
  server/service/game/eventHandlers/matchHandler.js
  server/service/game/eventHandlers/sendChattingMessageHandler.js
Labels: be, fe

#412 [develop <- game-page-ui-refactor] 게임 페이지 UI 개선
  client/package.json
  client/public/reset.css
  client/src/assets/background.png
  client/src/assets/exit.png
  client/src/assets/main-logo-large-old.png
  client/src/assets/main-logo-large.png
  client/src/assets/timer.png
  client/src/config.js
  client/src/presentation/components/Buttons/CandidateButton.jsx
  client/src/presentation/components/ChattingRow.jsx
  client/src/presentation/components/Message.jsx
  client/src/presentation/components/Nickname.jsx
  client/src/presentation/components/PlayerProfile.jsx
  client/src/presentation/components/ScoreBoardScoreRow.jsx
  client/src/presentation/components/StreamerVideo.jsx
  client/src/presentation/components/TextInput.jsx
  client/src/presentation/components/Timer.jsx
  client/src/presentation/components/UnderlinedLetter.jsx
  client/src/presentation/containers/ChattingPanel.jsx
  client/src/presentation/containers/MobileChattingPanel.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/containers/StreamingPanel/style.js
  client/src/presentation/containers/WordCandidates.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/presentation/pages/Game/style.js
  client/src/presentation/pages/MainPage.jsx
  client/src/presentation/pages/Ranking/style.js
  yarn.lock
Labels: css, fe, publishing

#415 [develop <- pair-game-system] 멀티세트 진행 및 기타 버그 (진행중)
  client/src/config.js
  client/src/presentation/components/StreamerVideo.jsx
  client/src/presentation/containers/StreamingPanel/index.js
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/StreamingManager.js
  client/src/store/globalReducer.js
  server/bin/www
  server/config.js
  server/service/game/controllers/gameController.js
  server/service/game/eventHandlers/connectPeerHandler.js
  server/service/game/eventHandlers/disconnectingHandler.js
  server/service/game/eventHandlers/sendChattingMessageHandler.js
  server/service/game/models/GameManager.js
  server/service/game/models/Timer.js
Labels: be, fe, ingame

#419 [develop <- end-game-panel-bug] 최종결과 화면 보이지 않는 에러 해결
  client/src/actions/index.js
  client/src/config.js
  client/src/constants/actionTypes.js
  client/src/service/ClientManager.js
  server/config.js
Labels: bug

#421 [develop <- environment-separation] 환경 분리 및 로컬 도커 환경 구성
  client/src/config.js
  client/src/service/ClientManager.js
  docker-compose-dev.yml
  package.json
Labels: environment

#422 [develop <- quiz-reselect-fix] 퀴즈 이중선택 방지 및 부정한 퀴즈 선택 방지
  server/config.js
  server/service/game/controllers/gameController.js
  server/service/game/eventHandlers/selectQuizHandler.js
Labels: bug

#424 [develop <- game-page-ui-refactor] 게임 페이지 UI 추가 작업
  client/public/index.html
  client/public/reset.css
  client/public/style.css
  client/src/App.jsx
  client/src/index.js
  client/src/presentation/components/Buttons/CandidateButton.jsx
  client/src/presentation/components/PlayerProfile.jsx
  client/src/presentation/pages/Game/style.js
  client/src/presentation/pages/MainPage.jsx
  client/src/presentation/pages/Ranking/style.js
  client/src/utils/styleColors.js
Labels: css, fe, publishing

#427 [develop <- fix-db-env] DB와 docker를 이용해 로컬 개발가능하게 하는 설정
  .gitignore
  docker-compose-dev.yml
  docker-compose.yml
  server/databaseFiles/databaseModels/seeder/index.js
Labels: bug, db, docker, fix

#430 [develop <- database-refactor] DatabaseManager 삭제, RankingRepository, QuizRepository 생성
  server/app.js
  server/bin/www
  server/controllers/api/ranking.js
  server/databaseFiles/DatabaseManager.js
  server/databaseFiles/databaseModels/seeder/index.js
  server/databaseFiles/databaseModels/seeder/ranking.csv
  server/databaseFiles/repositories/QuizRepository.js
  server/databaseFiles/repositories/RankingRepository.js
  server/databaseFiles/repositories/index.js
  server/databaseFiles/repositories/utils.js
  server/routes/api.js
  server/routes/api/ranking.js
  server/routes/paths/index.js
Labels: refactor

#433 [develop <- profile-score] 점수 변화시 좌측 점수 패널 표시 변경 구현
  client/src/constants/events.js
  client/src/service/GameManager.js
  server/service/game/eventHandlers/sendChattingMessageHandler.js
Labels: be, fe, ingame

#429 [develop <- fix-endset-message-error] 퀴즈 고르는 중에 스트리머가 나가 세트가 끝나면 뷰어에게 메세지가 사라지지 않는 버그 해결
  client/src/service/GameManager.js
  client/src/store/globalReducer.js
Labels: api, ask question, backlog, fe, fix

#436 [develop <- client-history-refactor] socket disconnect시 history를 사용하도록 수정
  client/src/constants/events.js
  client/src/presentation/pages/Game/index.js
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
Labels: fe, react, socket

#440 [develop <- feature-database-insert-select] 단어 선정, 플레이어 정보 저장
  client/src/presentation/pages/Game/style.js
  server/service/game/controllers/gameController.js
Labels: be, database

#444 [develop <- fix-error-user-leave] 유저가 방을 나갈 경우의 에러 처리
  server/service/game/eventHandlers/disconnectingHandler.js
  server/service/game/models/GameManager.js
Labels: bug, fix

#447 [develop <- fix-error-player-leave] 유저가 방을 나갔을 경우에 대한 방어 로직 추가
  server/service/game/eventHandlers/connectPeerHandler.js
  server/service/game/models/GameManager.js
Labels: be, bug, fix

#454 [develop <- remove-ranking-seed] 프로덕션에서 불필요한 initialize 데이터를 제거
  server/bin/www
Labels: be, db

#445 [develop <- feature more button] 무한스크롤을 더보기 버튼으로 수정
  client/package.json
  client/src/api/index.js
  client/src/presentation/components/Buttons/MoreButton.jsx
  client/src/presentation/components/Buttons/index.js
  client/src/presentation/containers/BottomRankPanel.jsx
  client/src/presentation/pages/Ranking/index.js
  client/src/presentation/pages/Ranking/style.js
  client/src/utils/styleColors.js
  server/config.js
  server/databaseFiles/repositories/RankingRepository.js
  server/routes/api.js
  server/routes/paths/index.js
  server/utils/getCurrentTime.js
  yarn.lock
Labels: api, be, fe, react

#455 [develop <- feature inactive user ban] 20초 동안 ready하지 않는 플레이어 강퇴
  client/src/actions/index.js
  client/src/constants/actionTypes.js
  client/src/constants/timer.js
  client/src/presentation/pages/Game/index.js
  client/src/service/ChattingManager.js
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/Timer.js
  client/src/store/globalReducer.js
  client/src/store/globalState.js
Labels: fe, react

#448 [develop <- refactor-game-page] 게임 페이지 커스텀 훅 적용
  client/src/config.js
  client/src/constants/events.js
  client/src/hooks/useInnerWidth.js
  client/src/hooks/useIsMobile.js
  client/src/hooks/useShiftingToWhichView.js
  client/src/presentation/pages/Game/index.js
Labels: react, refactor

#476 [develop <- round-set-visualize] 중간 점수 단계에 라운드와 세트 표기
  client/src/config.js
  client/src/service/GameManager.js
  server/config.js
  server/service/game/controllers/gameController.js
  server/service/game/eventHandlers/connectPeerHandler.js
  server/service/game/eventHandlers/disconnectingHandler.js
  server/service/game/models/GameManager.js
Labels: be, fe

#473 [develop <- ban-disconnected-player] 게임 중 카메라 연결이 안 될 경우, 플레이어 추방
  server/service/game/controllers/gameController.js
  server/service/game/models/GameManager.js
Labels: be, bug, fix

#477 [develop <- ui-refactor] 전체 페이지 UI개선
  client/src/assets/exit-black.png
  client/src/config.js
  client/src/presentation/components/Buttons/CandidateButton.jsx
  client/src/presentation/components/Buttons/ExitButton.jsx
  client/src/presentation/components/InputWindow.jsx
  client/src/presentation/components/Nickname.jsx
  client/src/presentation/components/RankPodium.jsx
  client/src/presentation/components/RankingRow.jsx
  client/src/presentation/components/ScoreBoardScoreRow.jsx
  client/src/presentation/containers/ChattingPanel.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/containers/StreamingPanel/style.js
  client/src/presentation/containers/WordCandidates.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/presentation/pages/Game/style.js
  client/src/presentation/pages/Ranking/index.js
  client/src/utils/styleColors.js
  server/service/game/eventHandlers/sendChattingMessageHandler.js
Labels: css, fe, publishing

#479 [develop <- fix-duplicate-answer] 정답을 맞힌 유저는 더이상 정답을 맞힐 수 없도록 수정
  client/src/presentation/containers/ChattingPanel.jsx
  server/service/game/eventHandlers/sendChattingMessageHandler.js
Labels: be, fe, fix, ingame, socket

#485 [develop <- share-room-url] 방 생성/ url 공유 기능 구현
  client/src/App.jsx
  client/src/assets/share.png
  client/src/constants/browser.js
  client/src/constants/button.js
  client/src/constants/events.js
  client/src/constants/timer.js
  client/src/presentation/components/Buttons/ShareUrlButton.jsx
  client/src/presentation/components/Buttons/index.js
  client/src/presentation/components/index.js
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/presentation/pages/Game/style.js
  client/src/service/ChattingManager.js
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/utils/copyUrlToClipboard.js
  client/src/utils/index.js
  client/src/utils/shareUrlButtonClickHandler.js
  server/app.js
  server/constants/events.js
  server/service/game/controllers/roomController.js
  server/service/game/eventHandlers/matchHandler.js
  server/service/game/models/GameManager.js
Labels: be, fe, react

#484 [develop <- display-correct-player] 정답을 맞힌 플레이어의 프로필 배경색 변경
  client/src/constants/events.js
  client/src/presentation/components/PlayerProfile.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/utils/styleColors.js
  server/service/game/controllers/gameController.js
  server/service/game/eventHandlers/sendChattingMessageHandler.js
Labels: be, fe, ingame

#489 [develop <- refactor-config-constants] config및 styleColors를 constants로 통합
  client/src/config.js
  client/src/constants/browser.js
  client/src/constants/game.js
  client/src/constants/inputConstraints.js
  client/src/constants/message.js
  client/src/constants/responsiveView.js
  client/src/constants/socket.js
  client/src/constants/styleColors.js
  client/src/constants/webRTC.js
  client/src/hooks/useShiftingToWhichView.js
  client/src/presentation/components/Buttons/style.js
  client/src/presentation/components/CenterTimer.jsx
  client/src/presentation/components/GameMessageBox.jsx
  client/src/presentation/components/InputWindow.jsx
  client/src/presentation/components/Message.jsx
  client/src/presentation/components/MessageInput.jsx
  client/src/presentation/components/Nickname.jsx
  client/src/presentation/components/PlayerProfile.jsx
  client/src/presentation/components/RankPodium.jsx
  client/src/presentation/components/RankingRow.jsx
  client/src/presentation/components/ScoreBoardScoreRow.jsx
  client/src/presentation/components/TextInput.jsx
  client/src/presentation/containers/BottomRankPanel.jsx
  client/src/presentation/containers/ChattingPanel.jsx
  client/src/presentation/containers/Introduction.jsx
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/containers/ScoreBoard.jsx
  client/src/presentation/containers/StreamingPanel/style.js
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/style.js
  client/src/service/ChattingManager.js
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/WebRTCManager.js
  client/src/utils/browserLocalStorage.js
  client/src/utils/constantValues.js
  client/src/utils/index.js
  client/src/utils/shareUrlButtonClickHandler.js
  client/src/utils/styleColors.js
Labels: setup

#486 [develop <- refactor-custom-hooks ] 리뷰어님 리뷰사항 반영
  client/src/hooks/useInnerWidth.js
  client/src/hooks/useShiftingToWhichView.js
Labels: fe, refactor

#487 [develop <- refactor-db-seeding] DB seed 방식을 명령어 방식에 추가
  server/databaseFiles/databaseModels/seeder/scripts/seedQuizzes.js
  server/package.json
Labels: db

#492 [develop <- refactor-server-game-controller] 서버의 게임 컨트롤러 리팩토링
  client/src/presentation/components/QuizDisplay.jsx
  server/service/game/controllers/gameController.js
  server/service/game/models/GameManager.js
Labels: refactor

#491 [develop <- refactor-game-page-index ] client Game 페이지 index 총체적 리팩토링 (in progress, 추후 또 PR 들어올 예정)
  client/src/actions/game.js
  client/src/actions/global.js
  client/src/actions/index.js
  client/src/constants/actionTypes.js
  client/src/constants/events.js
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/presentation/pages/Game/store/gameReducer.js
  client/src/presentation/pages/Game/store/gameState.js
  client/src/presentation/pages/Game/store/index.js
  client/src/presentation/pages/Game/style.js
Labels: fe, react, refactor

#498 [develop <- refactor-server-game-controller] 서버의 gameController 리팩토링
  .vscode/settings.json
  server/service/game/controllers/gameController.js
Labels: refactor

#499 [develop <- fix-ingame-error] 게임 정답을 여러번 치거나, 채팅을 하지 못하는 문제 해결
  server/service/game/controllers/gameController.js
Labels: bug, fix

#500 서버 상수 외부화(추후 PR 추가 전송할 예정)
  .vscode/settings.json
  server/constants/databaseConnections.js
  server/constants/events.js
  server/constants/gameRules.js
  server/constants/gameStatus.js
  server/service/game/controllers/gameController.js
Labels: refactor

#501 [develop <- refactor-game-page-index ] Game 페이지 index 리팩토링, 함수분리, 함수위치정리
  client/src/presentation/pages/Game/index.js
Labels: fe, react, refactor

#509 [develop <- refactor-server-handlers] 서버사이드 핸들러 리팩토링
  server/config.js
  server/service/game/controllers/gameController.js
  server/service/game/eventHandlers/disconnectingHandler.js
  server/service/game/eventHandlers/matchHandler.js
  server/service/game/eventHandlers/sendChattingMessageHandler.js
  server/service/game/models/GameManager.js
Labels: be, fe, refactor

#512 [develop <- fix toast rerendering bug] Toast 재렌더링 버그 수정
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/MainPage.jsx
Labels: fe, fix, react

#513 [develop <- test-game-page ] Game 페이지 컴포넌트 index에 Test 적용 및 그에 따른 warning 수정
  client/.eslintrc.json
  client/package.json
  client/src/__test__/Game.test.js
  client/src/presentation/components/Buttons/ExitButton.jsx
  client/src/presentation/components/Buttons/MenuButton.jsx
  client/src/presentation/components/Buttons/ShareUrlButton.jsx
  client/src/presentation/components/ChattingRow.jsx
  client/src/presentation/components/ChattingWindow.jsx
  client/src/presentation/components/InputWindow.jsx
  client/src/presentation/components/MessageInput.jsx
  client/src/presentation/components/PlayerProfile.jsx
  client/src/presentation/components/RankPodium.jsx
  client/src/presentation/components/TextInput.jsx
  client/src/presentation/components/Toast.jsx
  client/src/presentation/containers/BottomRankPanel.jsx
  client/src/presentation/containers/ChattingPanel.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/containers/StreamingPanel/index.js
  client/src/presentation/containers/StreamingPanel/presenter.js
  client/src/presentation/containers/TopRankPanel.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/store/globalState.js
  yarn.lock
Labels: fe, react, refactor

#507 [develop <- refactor-ready-button-visibility] 모바일과 데스크탑의 레디버튼이 실제로 렌더링 되지않게 조건 수정
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
Labels: fe, fix, react

#518 [ develop <- fix-gamepage-react-lifecycle ] Play with friends 기능에 접근 불가한 버그 수정
  client/src/constants/events.js
  client/src/presentation/pages/Game/index.js
  client/src/service/ClientManager.js
Labels: fe, fix

#524 Setup : docker-compose의 dev옵션에서 trycatch 제거
  docker-compose-dev.yml
Labels: setup

#522 [develop <- publish-round-set] 세트 종료 메시지 변경
  client/src/service/GameManager.js
Labels: publishing

#525 [develop <- refactor directory file] 불필요한 파일 및 폴더 삭제
  client/public/logo192.png
  client/public/logo512.png
  client/src/presentation/routes/index.js
  client/src/service/index.js
  client/src/service/socket/SocketClient.js
  client/src/service/socket/config.js
  server/constants/api.js
  server/public/index.html
  server/public/javascripts/config.js
  server/public/javascripts/index.js
  server/public/javascripts/webrtc-adapter.js
  server/public/stylesheets/style.css
  server/routes/api.js
  server/routes/paths/index.js
Labels: refactor

#529 [develop <- test-server-game-manager] 서버의 게임매니저 파일 테스트 코드 추가
  server/__test__/GameManager.test.js
  server/package.json
Labels: test

#530 [develop <- fix-server-timer-variable] 타이머 변수명 변경
  server/constants/timer.js
  server/service/game/models/Timer.js
Labels: refactor

#528 [develop <- fix-server-handler]
  server/service/game/controllers/gameController.js
  server/service/game/eventHandlers/connectPeerHandler.js
  server/service/game/eventHandlers/disconnectingHandler.js
  server/service/game/models/GameManager.js
Labels: be, refactor

#527 [develop <- refactor-play-with-friends ] 비공개방 관련 리팩토링 적용
  client/src/actions/global.js
  client/src/constants/actionTypes.js
  client/src/constants/events.js
  client/src/constants/message.js
  client/src/constants/timer.js
  client/src/hooks/useToast.js
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/pages/Game/index.js
  client/src/presentation/pages/Game/presenter.jsx
  client/src/service/ClientManager.js
  client/src/store/globalReducer.js
  client/src/store/globalState.js
  client/src/utils/createShareUrlButtonClickHandler.js
  client/src/utils/index.js
  client/src/utils/shareUrlButtonClickHandler.js
  server/constants/event.js
  server/service/game/eventHandlers/matchHandler.js
Labels: fix, react, refactor

#536 [develop <- refactor-repeat-set] repeatSet 함수 분리
  server/service/game/controllers/gameController.js
  server/service/game/eventHandlers/disconnectingHandler.js
Labels: refactor

#540 [develop <- chore ] index.html의 불필요한 link 태그 제거
  client/public/index.html
Labels: refactor

#543 [master <- docs] README.md 수정
  README.md
Labels: docs
