Repository connect-foundation/2019-09, pull requests merged in 2019-11, with the labels that each got.

#118 develop으로 pair-init merge
  .gitignore
  .prettierrc
  .vscode/settings.json
  docker-compose.yml
  nginx/default.conf.template
  package.json
  sample.env
  server/.eslintrc.json
  server/app.js
  server/bin/www
  server/package-lock.json
  server/package.json
  server/public/index.html
  server/public/javascripts/index.js
  server/public/javascripts/webrtc-adapter.js
  server/public/stylesheets/style.css
  yarn.lock
Labels: week2

#126 develop으로 fix-nginx-websocket merge
  nginx/default.conf.template
  sample.env
Labels: fix, nginx, setup

#131 master로 docs merge
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: docs

#132 develop으로 pair-react-setup merge
  .gitignore
  client/.eslintrc.json
  client/config/env.js
  client/config/jest/cssTransform.js
  client/config/jest/fileTransform.js
  client/config/modules.js
  client/config/paths.js
  client/config/pnpTs.js
  client/config/webpack.config.js
  client/config/webpackDevServer.config.js
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/scripts/build.js
  client/scripts/start.js
  client/scripts/test.js
  client/src/App.jsx
  client/src/api/index.js
  client/src/assets/main-logo-large.png
  client/src/index.js
  client/src/presentation/components/index.jsx
  client/src/presentation/containers/index.jsx
  client/src/presentation/pages/index.jsx
  client/src/presentation/routes/index.js
  client/src/service/index.js
  client/src/store/index.js
  client/src/utils/index.js
  package.json
  server/.eslintrc.json
  server/app.js
  server/public/javascripts/index.js
  yarn.lock
Labels: fe, react, setup

#154 develop으로 pair-component-logo merge
  client/package.json
  client/src/App.jsx
  client/src/presentation/components/index.js
  client/src/presentation/components/index.jsx
  client/src/presentation/components/logo.jsx
  client/src/presentation/containers/index.js
  client/src/presentation/containers/index.jsx
  client/src/presentation/containers/main-title.jsx
  client/src/presentation/pages/index.js
  client/src/presentation/pages/index.jsx
  client/src/presentation/pages/main-page.jsx
  yarn.lock
Labels: fe, react

#172 develop으로 pair container menu merge
  client/.eslintrc.json
  client/src/App.jsx
  client/src/presentation/components/Buttons/LargeButton.jsx
  client/src/presentation/components/Buttons/SmallButton.jsx
  client/src/presentation/components/Buttons/index.js
  client/src/presentation/components/Description.jsx
  client/src/presentation/components/Logo.jsx
  client/src/presentation/components/TextInput.jsx
  client/src/presentation/components/Title.jsx
  client/src/presentation/components/index.js
  client/src/presentation/containers/HowToPlay.jsx
  client/src/presentation/containers/MainTitle.jsx
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/containers/index.js
  client/src/presentation/pages/MainPage.jsx
  client/src/presentation/pages/index.js
Labels: fe, react

#171 develop <- pair-webrtc-room 화요일 마무리 PR
  server/.eslintrc.json
  server/app.js
  server/config.js
  server/public/index.html
  server/public/javascripts/config.js
  server/public/javascripts/index.js
  server/socket/index.js
  server/socket/utils.js
Labels: webrtc

#175 Pair container menu refactor
  client/src/config.js
  client/src/presentation/components/Buttons/LargeButton.jsx
  client/src/presentation/containers/HowToPlay.jsx
  client/src/presentation/containers/Menu.jsx
Labels: fe, issue, react, refactor

#182 develop으로 pair-webrtc-room-refactor merge
  server/public/javascripts/index.js
  server/socket/index.js
  server/socket/utils.js
Labels: refactor, webrtc

#207 [develop <- pair-react] Sprint 03 Day 03 pull request
  client/package.json
  client/public/index.html
  client/public/reset.css
  client/src/App.jsx
  client/src/Root.jsx
  client/src/index.js
  client/src/presentation/components/Buttons/LargeButton.jsx
  client/src/presentation/components/Description.jsx
  client/src/presentation/components/QuizDisplay.jsx
  client/src/presentation/components/StreamerVideo.jsx
  client/src/presentation/components/TextInput.jsx
  client/src/presentation/components/Timer.jsx
  client/src/presentation/components/UnderlinedLetter.jsx
  client/src/presentation/components/UnderlinedSpace.jsx
  client/src/presentation/components/index.js
  client/src/presentation/containers/Candidates.jsx
  client/src/presentation/containers/HowToPlay.jsx
  client/src/presentation/containers/MainTitle.jsx
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/containers/StreamingPanel.jsx
  client/src/presentation/containers/index.js
  client/src/presentation/pages/Game.jsx
  client/src/presentation/pages/MainPage.jsx
  client/src/presentation/pages/index.js
  yarn.lock
Labels: fe, react

#204 develop으로 pair-webrtc-connection merge
  server/config.js
  server/public/javascripts/index.js
  server/socket/index.js
  server/socket/utils.js
Labels: be, fe, webrtc

#210 [develop <- pair-react-refactor] 코드 리뷰 사항 반영
  client/src/App.jsx
  client/src/Root.jsx
  client/src/index.js
  client/src/presentation/components/Buttons/index.js
  client/src/presentation/components/QuizDisplay.jsx
  client/src/presentation/components/StreamerVideo.jsx
  client/src/presentation/components/index.js
  client/src/presentation/containers/StreamingPanel.jsx
  client/src/presentation/containers/WordCandidates.jsx
  client/src/presentation/containers/index.js
  client/src/presentation/pages/Game.jsx
  client/src/presentation/pages/index.js
Labels: fe, react, refactor

#209 develop으로 pair-webrtc-connection-refactor merge
  server/public/javascripts/config.js
  server/public/javascripts/index.js
  server/socket/utils.js
Labels: be, fe, refactor, webrtc

#226 [develop <- pair-react-webRTC-merge] Sprint 03 pull request
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/reset.css
  client/src/App.jsx
  client/src/contexts/DispatchContext.js
  client/src/contexts/GlobalContext.js
  client/src/contexts/index.js
  client/src/presentation/components/Buttons/LargeButton.jsx
  client/src/presentation/components/Description.jsx
  client/src/presentation/components/StreamerVideo.jsx
  client/src/presentation/components/TextInput.jsx
  client/src/presentation/components/Timer.jsx
  client/src/presentation/components/Title.jsx
  client/src/presentation/containers/HowToPlay.jsx
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/pages/Game.jsx
  client/src/presentation/pages/MainPage.jsx
  client/src/service/socket/SocketClient.js
  client/src/service/socket/config.js
  server/bin/www
  server/socket/index.js
  yarn.lock
Labels: react, webrtc

#245 develop으로 pair-client-refactor merge
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/StreamingManager.js
  client/src/service/WebRTCManager.js
  client/src/service/config.js
Labels: fe, refactor

#267 Pair game system
  client/src/presentation/pages/Game.jsx
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/StreamingManager.js
  server/.eslintrc.json
  server/old-socket/index.js
  server/old-socket/utils.js
  server/package.json
  server/socket/handlers/index.js
  server/socket/handlers/matchHandler.js
  server/socket/handlers/sendReadyHandler.js
  server/socket/index.js
  server/socket/io.js
  server/socket/rooms.js
  yarn.lock
Labels: be, fe, socket

#281 [develop <- pair-game-system] 영상송출 및 게임시작 부분적완료
  client/src/presentation/containers/Menu.jsx
  client/src/presentation/containers/PlayerPanel.jsx
  client/src/presentation/pages/Game.jsx
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/StreamingManager.js
  client/src/service/WebRTCManager.js
  server/config.js
  server/socket/handlers/disconnectingHandler.js
  server/socket/handlers/index.js
  server/socket/handlers/matchHandler.js
  server/socket/handlers/sendReadyHandler.js
  server/socket/index.js
  server/socket/rooms.js
Labels: be, fe, ingame, webrtc

#295 [develop <- pair-game-system] chatting system과의 머지를 위한 PR
  client/src/service/ClientManager.js
  client/src/service/GameManager.js
  client/src/service/StreamingManager.js
  client/src/utils/index.js
  client/src/utils/makeViewPlayerList.js
  server/socket/gameController.js
  server/socket/handlers/disconnectingHandler.js
  server/socket/handlers/index.js
  server/socket/handlers/sendReadyHandler.js
  server/socket/rooms.js
Labels: be, fe, socket

#305 [develop <- feature-reset-chatting] 채팅방 리셋 기능 추가
  client/src/service/ClientManager.js
Labels: fe, react

#304 [develop <- feature-video-inversion] merge
  client/src/presentation/components/StreamerVideo.jsx
Labels: css, fe
